---
output:
  pdf_document: default
  html_document: default
---
---
title: "ExampleRMarkdown"
author: "Naivy Rodal"
date: "01/29/202"
output: html_document

```{r global_options, include= FALSE}
knitr::opts_chunk$set(message=FALSE)
tidy.opts=list(width.cutoff=60)
```

```{r}
library(pander)
norm<- rnorm(100, mean=0, sd=1)
```
```{r}
A<- c("a","a","b", "b")
B<- c(5, 10, 15, 20)
dataframe<- data.frame(A,B)
plot(dataframe)
```

```{r, include= FALSE}
library(pander)
plant<- c("a", "b")
temperature<- c(20,20)
growth<- c(0.65, 0.95)
dataframe<- data.frame(plant, temperature, growth)
emphasize.italics.cols(2)
pander(dataframe)
```
|Plant| Temp | Growth |
|:----|:-----|-------:|
|A    | 20   | 0.65   |
|B    | 20   | 0.95   |

```{r, echo=FALSE} 
library(broom)
A<- c(20, 15, 10)
B<- c(1,2,3)
lm_test <- lm(A~B)
summary(lm_test)
table_obj<- tidy(lm_test)
pander(table_obj,digits=3)
```
```{r global_options, include= FALSE}
knitr::opts_chunk$set(message=FALSE)
tidy.opts=list(width.cutoff=60)
```
- - -
title: "R Markdown Tutorial Demo"
author: "Naivy Rodal"
date: "01/30/2020"
output: pdf document
latex_engine: xelatex
geometry: left= 0.5cm, right= 1cm, top= 1cm, bottom= 1cm
mainfont: Arial
- - -
\pagebreak
```{r}
"Codey codey code code"
```






